# Отключаем новую архитектуру (совместимость с react-native-screens и др.)
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

project 'BirthdayApp.xcodeproj'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'BirthdayApp' do
  config = use_native_modules!
  use_frameworks! :linkage => (ENV['USE_FRAMEWORKS'] == '1' ? :dynamic : :static)

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    # Устанавливаем минимальный deployment target для всех подов (убирает предупреждение про 9.0)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      end
    end
  end
end
